/*
  Register definitions for slave core: Wishbone IRIG-B

  * File           : interface.h
  * Author         : auto-generated by wbgen2 from interfaz.wb
  * Created        : Mon Mar 10 09:06:15 2014
  * Standard       : ANSI C

    THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE interfaz.wb
    DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!

*/

#ifndef __WBGEN2_REGDEFS_INTERFAZ_WB
#define __WBGEN2_REGDEFS_INTERFAZ_WB

#include <inttypes.h>

#if defined( __GNUC__)
#define PACKED __attribute__ ((packed))
#else
#error "Unsupported compiler?"
#endif

#ifndef __WBGEN2_MACROS_DEFINED__
#define __WBGEN2_MACROS_DEFINED__
#define WBGEN2_GEN_MASK(offset, size) (((1<<(size))-1) << (offset))
#define WBGEN2_GEN_WRITE(value, offset, size) (((value) & ((1<<(size))-1)) << (offset))
#define WBGEN2_GEN_READ(reg, offset, size) (((reg) >> (offset)) & ((1<<(size))-1))
#define WBGEN2_SIGN_EXTEND(value, bits) (((value) & (1<<bits) ? ~((1<<(bits))-1): 0 ) | (value))
#endif


/* definitions for register: Status Control Register */

/* definitions for field: Reset bit in reg: Status Control Register */
#define IRIGB_STAT_RES                        WBGEN2_GEN_MASK(0, 1)

/* definitions for field: Enable bit in reg: Status Control Register */
#define IRIGB_STAT_ENA                        WBGEN2_GEN_MASK(1, 1)

/* definitions for register: Year Data Register */

/* definitions for field: Year value in reg: Year Data Register */
#define IRIGB_YEA_YEAR_MASK                   WBGEN2_GEN_MASK(0, 32)
#define IRIGB_YEA_YEAR_SHIFT                  0
#define IRIGB_YEA_YEAR_W(value)               WBGEN2_GEN_WRITE(value, 0, 32)
#define IRIGB_YEA_YEAR_R(reg)                 WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Day Data Register */

/* definitions for field: Day value in reg: Day Data Register */
#define IRIGB_DAY_DAY_MASK                    WBGEN2_GEN_MASK(0, 32)
#define IRIGB_DAY_DAY_SHIFT                   0
#define IRIGB_DAY_DAY_W(value)                WBGEN2_GEN_WRITE(value, 0, 32)
#define IRIGB_DAY_DAY_R(reg)                  WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Hour Data Register */

/* definitions for field: Hour value in reg: Hour Data Register */
#define IRIGB_HOU_HOU_MASK                    WBGEN2_GEN_MASK(0, 32)
#define IRIGB_HOU_HOU_SHIFT                   0
#define IRIGB_HOU_HOU_W(value)                WBGEN2_GEN_WRITE(value, 0, 32)
#define IRIGB_HOU_HOU_R(reg)                  WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Minute Data Register */

/* definitions for field: Minute value in reg: Minute Data Register */
#define IRIGB_MIN_MIN_MASK                    WBGEN2_GEN_MASK(0, 32)
#define IRIGB_MIN_MIN_SHIFT                   0
#define IRIGB_MIN_MIN_W(value)                WBGEN2_GEN_WRITE(value, 0, 32)
#define IRIGB_MIN_MIN_R(reg)                  WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Second Data Register */

/* definitions for field: Second value in reg: Second Data Register */
#define IRIGB_SEC_SEC_MASK                    WBGEN2_GEN_MASK(0, 32)
#define IRIGB_SEC_SEC_SHIFT                   0
#define IRIGB_SEC_SEC_W(value)                WBGEN2_GEN_WRITE(value, 0, 32)
#define IRIGB_SEC_SEC_R(reg)                  WBGEN2_GEN_READ(reg, 0, 32)

/* definitions for register: Interrupt disable register */

/* definitions for field: Hour update request in reg: Interrupt disable register */
#define IRIGB_EIC_IDR_HUR                     WBGEN2_GEN_MASK(0, 1)

/* definitions for register: Interrupt enable register */

/* definitions for field: Hour update request in reg: Interrupt enable register */
#define IRIGB_EIC_IER_HUR                     WBGEN2_GEN_MASK(0, 1)

/* definitions for register: Interrupt mask register */

/* definitions for field: Hour update request in reg: Interrupt mask register */
#define IRIGB_EIC_IMR_HUR                     WBGEN2_GEN_MASK(0, 1)

/* definitions for register: Interrupt status register */

/* definitions for field: Hour update request in reg: Interrupt status register */
#define IRIGB_EIC_ISR_HUR                     WBGEN2_GEN_MASK(0, 1)

PACKED struct IRIGB_WB {
  /* [0x0]: REG Status Control Register */
  uint32_t STAT;
  /* [0x4]: REG Year Data Register */
  uint32_t YEA;
  /* [0x8]: REG Day Data Register */
  uint32_t DAY;
  /* [0xc]: REG Hour Data Register */
  uint32_t HOU;
  /* [0x10]: REG Minute Data Register */
  uint32_t MIN;
  /* [0x14]: REG Second Data Register */
  uint32_t SEC;
  /* padding to: 8 words */
  uint32_t __padding_0[2];
  /* [0x20]: REG Interrupt disable register */
  uint32_t EIC_IDR;
  /* [0x24]: REG Interrupt enable register */
  uint32_t EIC_IER;
  /* [0x28]: REG Interrupt mask register */
  uint32_t EIC_IMR;
  /* [0x2c]: REG Interrupt status register */
  uint32_t EIC_ISR;
};

#endif
